"""catalogo adoption metadata

Revision ID: 0869e7146638
Revises: f2b2570aed04
Create Date: 2026-09-05 20:12:14.890793

Manually trimmed from the autogenerated diff: autogenerate also detected the
rag-api service tables (`catalogo_productos_rag`, `catalogo_amx_rag`) as
untracked and wanted to DROP them. Those tables belong to the sibling RAG
service and MUST NOT be touched here — this migration only adds the five
nullable `catalogo` columns. No `CREATE EXTENSION vector` is needed (exists).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0869e7146638"
down_revision: str | None = "f2b2570aed04"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Add nullable RAG-adoption metadata columns to `catalogo`."""
    op.add_column("catalogo", sa.Column("marca", sa.String(length=300), nullable=True))
    op.add_column("catalogo", sa.Column("categoria", sa.String(length=300), nullable=True))
    op.add_column("catalogo", sa.Column("subcategoria", sa.String(length=300), nullable=True))
    op.add_column("catalogo", sa.Column("moneda", sa.String(length=3), nullable=True))
    op.add_column("catalogo", sa.Column("origen", postgresql.JSONB(astext_type=sa.Text()), nullable=True))


def downgrade() -> None:
    """Drop the adoption metadata columns (back up adopted rows first)."""
    op.drop_column("catalogo", "origen")
    op.drop_column("catalogo", "moneda")
    op.drop_column("catalogo", "subcategoria")
    op.drop_column("catalogo", "categoria")
    op.drop_column("catalogo", "marca")