"""initial schema with pgvector

Revision ID: 26a4a1b103fe
Revises:
Create Date: 2026-08-19 21:47:14.408225
"""

from collections.abc import Sequence

import pgvector
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "26a4a1b103fe"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # pgvector extension powers the catalogo.embedding vector(1536) column.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lista_precios",
        sa.Column("lista_id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=120), nullable=False),
        sa.Column("descuento_lista_pct", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.PrimaryKeyConstraint("lista_id"),
        sa.UniqueConstraint("nombre"),
    )
    op.create_table(
        "proveedores",
        sa.Column("proveedor_id", sa.Integer(), nullable=False),
        sa.Column("razon_social", sa.String(length=200), nullable=False),
        sa.Column("contacto", sa.String(length=200), nullable=True),
        sa.Column("telefono", sa.String(length=32), nullable=True),
        sa.Column("margen_predeterminado", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("condiciones", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("proveedor_id"),
    )
    op.create_table(
        "catalogo",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("codigo_interno", sa.String(length=64), nullable=False),
        sa.Column("codigo_barras", sa.String(length=64), nullable=True),
        sa.Column("proveedor_id", sa.Integer(), nullable=False),
        sa.Column("nombre_oficial", sa.String(length=300), nullable=False),
        sa.Column("costo_proveedor", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("margen_aplicado_pct", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("precio_lista_base", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("stock_disponible", sa.Integer(), nullable=False),
        sa.Column("sinonimos", sa.ARRAY(sa.Text()), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
        sa.ForeignKeyConstraint(
            ["proveedor_id"],
            ["proveedores.proveedor_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_catalogo_codigo_interno"), "catalogo", ["codigo_interno"], unique=True)
    op.create_table(
        "clientes",
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("nombre_comercial", sa.String(length=200), nullable=False),
        sa.Column("contacto", sa.String(length=200), nullable=True),
        sa.Column("telefono_norm", sa.String(length=32), nullable=False),
        sa.Column("lista_precios_id", sa.Integer(), nullable=False),
        sa.Column("descuento_particular_pct", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.ForeignKeyConstraint(
            ["lista_precios_id"],
            ["lista_precios.lista_id"],
        ),
        sa.PrimaryKeyConstraint("customer_id"),
    )
    op.create_index(op.f("ix_clientes_telefono_norm"), "clientes", ["telefono_norm"], unique=True)
    op.create_table(
        "proveedor_sku_mapping",
        sa.Column("mapping_id", sa.Integer(), nullable=False),
        sa.Column("proveedor_id", sa.Integer(), nullable=False),
        sa.Column("codigo_proveedor", sa.String(length=64), nullable=False),
        sa.Column("descripcion_raw", sa.Text(), nullable=True),
        sa.Column("sku_interno", sa.String(length=64), nullable=False),
        sa.Column("confianza", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.ForeignKeyConstraint(
            ["proveedor_id"],
            ["proveedores.proveedor_id"],
        ),
        sa.PrimaryKeyConstraint("mapping_id"),
    )
    op.create_table(
        "orders",
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column(
            "estado",
            sa.Enum("PENDING_APPROVAL", "APPROVED", "IN_DISPATCH", "REJECTED", name="order_estado"),
            nullable=False,
        ),
        sa.Column("needs_requote", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rejected_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["clientes.customer_id"],
        ),
        sa.PrimaryKeyConstraint("order_id"),
    )
    op.create_table(
        "order_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("sku", sa.String(length=64), nullable=False),
        sa.Column("cantidad", sa.Integer(), nullable=False),
        sa.Column("base_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("final_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("adjustment", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.order_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "stock_reservations",
        sa.Column("reservation_id", sa.Integer(), nullable=False),
        sa.Column("sku", sa.String(length=64), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=True),
        sa.Column("cantidad", sa.Integer(), nullable=False),
        sa.Column(
            "timestamp", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("ttl_minutes", sa.Integer(), nullable=False),
        sa.Column(
            "estado",
            sa.Enum("ACTIVE", "CONVERTED", "RELEASED", "EXPIRED", name="reservation_estado"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["clientes.customer_id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.order_id"],
        ),
        sa.PrimaryKeyConstraint("reservation_id"),
    )
    op.create_index(op.f("ix_stock_reservations_sku"), "stock_reservations", ["sku"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_stock_reservations_sku"), table_name="stock_reservations")
    op.drop_table("stock_reservations")
    op.drop_table("order_items")
    op.drop_table("orders")
    op.drop_table("proveedor_sku_mapping")
    op.drop_index(op.f("ix_clientes_telefono_norm"), table_name="clientes")
    op.drop_table("clientes")
    op.drop_index(op.f("ix_catalogo_codigo_interno"), table_name="catalogo")
    op.drop_table("catalogo")
    op.drop_table("proveedores")
    op.drop_table("lista_precios")
    op.execute("DROP EXTENSION IF EXISTS vector")
    # ### end Alembic commands ###
