"""add stock_adjustments

Revision ID: b2f353dfc3d2
Revises: 26a4a1b103fe
Create Date: 2026-08-22 18:50:53.920295
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b2f353dfc3d2"
down_revision: str | None = "26a4a1b103fe"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stock_adjustments",
        sa.Column("adjustment_id", sa.Integer(), nullable=False),
        sa.Column("sku", sa.String(length=64), nullable=False),
        sa.Column("delta", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(length=300), nullable=False),
        sa.Column("actor", sa.String(length=120), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("adjustment_id"),
    )
    op.create_index(op.f("ix_stock_adjustments_sku"), "stock_adjustments", ["sku"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_stock_adjustments_sku"), table_name="stock_adjustments")
    op.drop_table("stock_adjustments")
    # ### end Alembic commands ###
